#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "[pre-commit hook] Starting...\n\n"

# Either lint and check types successfully or print errors and exit
(yarn lint-staged && yarn types:check) || exit 1;

git diff --staged 

# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty

while true; do
  read -p "[pre-commit hook] Are staged changes correct? (Y/n) " yn
  case $yn in
      [Yy] ) echo "'Everything is correct! Continuing...\n\n'"; break;;
      [Nn] ) echo "Aborting process! Staged changes have flaws.\n\n"; exit 1;;
      * ) echo "Please answer y or n for yes or no.\n\n";;
  esac
done

